/// <reference types="vite/client" />
import type { AsiApi } from '@shared/api'
import type { Friend } from '@shared/models'
import type { DetectedPreset } from '@shared/presets'
import type { AttachmentKind } from '@shared/events'
import type { PaletteResult, SearchTarget } from '@shared/search'

declare global {
  interface Window {
    asi: { doodle: { open(workspaceId: string, opts?: { chatId?: string; name?: string }): Promise<void>; list(wsId: string): Promise<{ name: string; updatedAt: number }[]>; newName(wsId: string): Promise<string>; load(wsId: string, name: string): Promise<string | null>; save(wsId: string, name: string, json: string): Promise<void>; send(wsId: string, chatId: string, name: string, pngBase64: string, note?: string): Promise<void>; reveal(wsId: string): Promise<void>; onOpen(cb: (a: { chatId: string | null; name: string | null }) => void): () => void }; search: { all(q: string): Promise<PaletteResult[]>; jump(t: SearchTarget): Promise<void>; openPalette(): Promise<void>; onFocus(cb: () => void): () => void }; attachments: { load(messageId: string): Promise<{ chatId: string; name: string; kind: AttachmentKind; text: string; path: string | null; friendName: string }>; open(messageId: string): Promise<void>; pickFiles(): Promise<string[]>; sendFiles(chatId: string, paths: string[], note?: string): Promise<void> }; platform: string; windowFocused(): Promise<boolean>; api: AsiApi; onChanged(cb: (topic: string) => void): () => void; pickFolder(): Promise<string | null>; chat: { send(chatId: string, text: string, quote?: { name: string; text: string }): Promise<unknown>; setMode(chatId: string, mode: string): Promise<void>; nudge(chatId: string): Promise<boolean>; openNextUnread(): Promise<string | null>; toastOpenChat(chatId: string): Promise<void>; toastDismiss(): Promise<void>; interrupt(chatId: string): Promise<void>; respond(chatId: string, reqId: string, answer: string, reason?: string): Promise<void>; openWindow(chatId: string): Promise<void> }; friends: { detect(): Promise<DetectedPreset[]>; availability(): Promise<Record<string, boolean>>; addPreset(id: string): Promise<Friend>; addCustom(c: { name: string; command: string; args: string[]; kind: 'acp' | 'pty' }): Promise<Friend>; testAcp(command: string, args: string[]): Promise<{ ok: true; agent: string } | { ok: false; error: string }>; openAddWindow(): Promise<void> }; safety: { setGlobalDangerous(on: boolean): Promise<void>; setFriendDangerous(id: string, on: boolean): Promise<void>; openOptions(): Promise<void> } }
  }
}
